server:
  port: 3000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orgs_and_workers
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: Postgres