# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - master
    - 'dev/*'
    - 'dependabot/*' 
        
  pull_request:
    branches: 
    - master
    - 'dependabot/*' 

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@HEAD
      with:
        working-directory: FrontEndApp
        useLockFile: false
    - run: npm run build
      working-directory: FrontEndApp
    - run: npm test
      working-directory: FrontEndApp
  build-back:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Postgresql-12
      run: sudo apt-get update && sudo apt-get install -y postgresql-12
      
    - name: Start cluster
      run: sudo pg_ctlcluster 12 main start
      
    - name: Create user for runner 
      run: sudo -u postgres bash -c "psql -c \"CREATE USER admin WITH PASSWORD '12345' SUPERUSER;CREATE USER runner WITH PASSWORD '12345' SUPERUSER;\""

    - name: Create database
      run: sudo -u postgres bash -c "psql -c \"CREATE DATABASE orgs_and_workers;\""

    - name: Setup database
      run: psql --dbname orgs_and_workers -f setup.sql
      working-directory: postgres
      env:
        PGPASSWORD: 12345

    - name: Generate code with jOOQ
      run: mvn generate-sources
      working-directory: WebServer
      
    - name: Test and send coverage
      run: mvn test jacoco:report
      working-directory: WebServer
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: WebServer

  test-postgres:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Postgresql-12
      run: sudo apt-get update && sudo apt-get install -y postgresql-12
      
    - name: Start cluster
      run: sudo pg_ctlcluster 12 main start
      
    - name: Create user for runner 
      run: sudo -u postgres bash -c "psql -c \"CREATE USER runner WITH PASSWORD '12345' SUPERUSER;\""

    - name: Create database
      run: sudo -u postgres bash -c "psql -c \"CREATE DATABASE orgs_and_workers;\""


    - name: clone PGTap
      run: git clone https://github.com/theory/pgtap
    
    - name: Make and Make install PGTap
      run: sudo make && sudo make install && make installcheck
      working-directory: pgtap
      env:
        PGPASSWORD: 12345
      
    - name: CPAN parser for pg_prove
      run: sudo cpan TAP::Parser::SourceHandler::pgTAP
      
    - name: Setup database
      run: psql --dbname orgs_and_workers -f setup.sql
      working-directory: postgres
      env:
        PGPASSWORD: 12345

    - name: Run tests
      run: pg_prove --dbname orgs_and_workers --port 5432 tests/*.sql
      working-directory: postgres 
      env:
        PGPASSWORD: 12345
