name: docker-push-to-docker-hub


on:
  push:
    branches: 
    - master

jobs:
  build-server-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rycarok/orgs_and_workers_server
        tags: latest