name: PostgresUnitTests

on:
  push:
    branches:  
    - master
    - 'dev/*'
    - '!dev/front*'
      
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Postgresql-12
      run: sudo apt-get update && sudo apt-get install -y postgresql-12
      
    - name: Start cluster
      run: sudo pg_ctlcluster 12 main start
      
    - name: Create user for runner 
      run: sudo -u postgres bash -c "psql -c \"CREATE USER runner WITH PASSWORD '12345' SUPERUSER;\""

    - name: Create database
      run: sudo -u postgres bash -c "psql -c \"CREATE DATABASE orgs_and_workers;\""


    - name: clone PGTap
      run: git clone https://github.com/theory/pgtap
    
    - name: Make and Make install PGTap
      run: sudo make && sudo make install && make installcheck
      working-directory: pgtap
      env:
        PGPASSWORD: 12345
      
    - name: CPAN parser for pg_prove
      run: sudo cpan TAP::Parser::SourceHandler::pgTAP
      
    - name: Setup database
      run: psql --dbname orgs_and_workers -f setup.sql
      working-directory: postgres
      env:
        PGPASSWORD: 12345

    - name: Run tests
      run: pg_prove --dbname orgs_and_workers --port 5432 tests/*.sql
      working-directory: postgres 
      env:
        PGPASSWORD: 12345
